ENTITY_EMOJIS = {
    "USA": "🇺🇸", 
    "United States": "🇺🇸",
    "China": "🇨🇳",
    "Japan": "🇯🇵",
    "Germany": "🇩🇪",
    "India": "🇮🇳",
    "UK": "🇬🇧", 
    "United Kingdom": "🇬🇧", 
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "France": "🇫🇷",
    "Brazil": "🇧🇷",
    "Canada": "🇨🇦",
    "S. Korea": "🇰🇷", 
    "South Korea": "🇰🇷",
    "Switzerland": "🇨🇭",
    "Norway": "🇳🇴",
    "Singapore": "🇸🇬",
    "Australia": "🇦🇺",
    "Nigeria": "🇳🇬",
    "Indonesia": "🇮🇩",
    "Russia": "🇷🇺", 
    "USSR/Russia": "🇷🇺",
    "Iceland": "🇮🇸",
    "Sweden": "🇸🇪",
    "Iran": "🇮🇷",
    "Pakistan": "🇵🇰",
    "Bangladesh": "🇧🇩",
    "Argentina": "🇦🇷",
    "Italy": "🇮🇹",
    "Spain": "🇪🇸",
    "Uruguay": "🇺🇾",
    
    # Tech / People
    "Elon Musk": "🚀",
    "Jeff Bezos": "📦",
    "Bernard Arnault": "👜",
    "Bill Gates": "💻",
    "Mark Zuckerberg": "📱",
    "Larry Ellison": "💾",
    "Warren Buffett": "📈",
    "Larry Page": "🔍",
    "Sergey Brin": "🔍",
    "Steve Ballmer": "🖥️",
    "Jensen Huang": "🕹️",
    "Tim Cook": "🍎",
    "Jack Dorsey": "🐦"
}
